# Secrets in use:
# PAT_FOR_LEGITIFY - a GitHub Personal Access Token (classic) with scopes:
#   admin:org, read:enterprise, admin:org_hook, read:org, repo, read:repo_hook

name: "Legitify Analyze"

on:
  workflow_dispatch:
  schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    - cron: "0 11 * * 1-5"
  pull_request:
    branches: ["*"]

jobs:
  analyze:
    name: Legitify SCM security scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Legitify Action
        uses: Legit-Labs/legitify@main
        with:
          github_token: ${{ secrets.PAT_FOR_LEGITIFY }}
          analyze_self_only: "true"
          scorecard: "verbose"
