# Mobb/SonarQube Fixer on pull requests.
#
# This workflow defines the needed steps to run SonarQube on every pull request
# and pass the results to Mobb Fixer.
#
# Secrets in use (add your missing ones):
#
# SONARQUBE_HOST_URL - your SonarQube server host. https://sonarcloud.io for cloud version.
# SONARQUBE_PROJECT - your SonarQube project name.
# SONARQUBE_ORG - your SonarQube organization name.
# SONARQUBE_TOKEN - your SonarQube access token.
# MOBB_API_TOKEN - your Mobb user API token.
# GITHUB_TOKEN - automatically set by GitHub.
#
name: "Mobb/Sonar"

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

jobs:
  scan-and-fix:
    name: Scan with SonarQube and fix with Mobb
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360

    permissions:
      pull-requests: write
      statuses: write
      contents: read
      actions: read

    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout repo to get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Setup Node on this machine
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pip requests
        run: pip install requests
          
      - name: Check env
        run: |
          echo "Branch is: $BRANCH"
          env
          
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONARQUBE_PROJECT }}
            -Dsonar.organization=${{ vars.SONARQUBE_ORG }}
            -Dsonar.branch.name=${{ env.BRANCH }}
            -Dsonar.token=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.host.url=${{ vars.SONARQUBE_HOST_URL }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/*.log,**/*.md
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Export SonarQube report
        if: always()
        run: |
          SONARQUBE_HOST_URL=${{ vars.SONARQUBE_HOST_URL }} \
          SONARQUBE_PROJECT=${{ vars.SONARQUBE_PROJECT }} \
          SONARQUBE_TOKEN=${{ secrets.SONARQUBE_TOKEN }} \
          SONARQUBE_ORG=${{ vars.SONARQUBE_ORG }} \
          BRANCH="$BRANCH" \
          REPORT_PATH=report.json \
          python .github/workflows/sonarqube_download_report.py

      - name: Archive SonarQube report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-report
          path: report.json
          retention-days: 30

      - name: Run Mobb on the findings and get fixes
        if: always()
        uses: mobb-dev/action@v1.1
        with:
          report-file: "report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
